on:
  workflow_call:
    inputs:
      app_type:
        required: true
        type: string
jobs:
  nodejs:
    runs-on: self-hosted
    if: inputs.app_type == 'nodejs'
    steps:
      - uses: actions/checkout@v4
      - name: Generating Artifacts
        run: |
          npm install;
          ls -ltr 

  java:
    runs-on: self-hosted
    if: inputs.app_type == 'java'
    steps:
      - uses: actions/checkout@v4
      - name: Generating Artifacts
        run: |
          mvn compile ; 
          mvn clean package;
          ls -ltr 

  python:
    runs-on: self-hosted
    if: inputs.app_type == 'python'
    steps:
      - uses: actions/checkout@v4
      - name: Generating Artifacts
        run: |
          sudo dnf install -y gcc python3-devel
          pip3 install -r requirements.txt
          ls -ltr
