on:
  workflow_call:
    inputs:
      app_type:
        required: true
        type: string
      component:
        required: true
        type: string
jobs:
  scan:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Running SAST Scan
        run: echo "Running Static Application Security Testing" 

  test:
    needs: scan
    uses: B60-CloudDevOps/roboshop-github-actions/.github/workflows/unit-testing.yml@main
    with:
        app_type: ${{ inputs.app_type }}

  build:
    needs: test
    uses: B60-CloudDevOps/roboshop-github-actions/.github/workflows/build.yml@main
    with:
        app_type: ${{ inputs.app_type }}
        component: ${{ inputs.component }}
      
  dev-deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Generating Artifacts
        run: echo "Performing deployment of artifact to Development Environment"

  qa-deploy:
    runs-on: self-hosted
    environment: qa-deploy
    needs: dev-deploy
    steps:
      - uses: actions/checkout@v4
      - name: Generating Artifacts
        run: echo "Performing deployment of artifact to QA Environment"

  preprod-deploy:
    runs-on: self-hosted
    environment: preprod-deploy
    needs: qa-deploy
    steps:
      - uses: actions/checkout@v4
      - name: Generating Artifacts
        run: echo "Performing deployment of artifact to Pre-Prod Environment"

  prod-deploy:
    runs-on: self-hosted
    environment: prod-deploy
    needs: preprod-deploy
    steps:
      - uses: actions/checkout@v4
      - name: Generating Artifacts
        run: echo "Performing deployment of artifact to Prod Environment"