on:
  workflow_call:
    inputs:
      app_type:
        required: true
        type: string
      component:
        required: true
        type: string
      app_env:
        required: true
        type: string
jobs:
  scan:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with: 
            repository: 'B60-CloudDevOps/roboshop-helm'
      - name: Printing GitSha
        run: | 
            echo ${GITHUB_SHA}