on:
  workflow_call:
    inputs:
      app_type:
        required: true
        type: string
      component:
        required: true
        type: string
      app_env:
        required: true
        type: string
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with: 
            repository: 'B60-CloudDevOps/roboshop-helm'  # This switches the repo to get the content of this repo
            path: helm  
      - name: Printing GitSha
        run: | 
            cd helm
            echo ${GITHUB_SHA}
            ls -ltr 
            pwd